# Banking and Finance project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  labels:
    app: myproject-lbl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: BankingFinance
    spec:
      containers:
      - name: financeme
        image: prashanthdruva/docker_assignment3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
  selector:
    matchLabels:
      app: BankingFinance

---
apiVersion: v1
kind: Service
metadata:
  name: myproject-service
  labels:
    app: myproject-lbl
spec:
  type: NodePort
  selector:
    app: BankingFinance
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31038